[package]
name = "sendToken"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "=1.10.2"
borsh = "0.9.3"
borsh-derive = "0.9.1"
spl-token = { version = "3.3",  features = [ "no-entrypoint" ] }


[features]
test-bpf = []

[lib]
crate-type = ["cdylib", "lib"]
